In [2]:
import numpy as np

In [3]:
np1 = np.array([1,2,3,4])
np2= np.array([5,6,7,8])

In [4]:
print(np1)
print(np2)
print(type(np1),type(np2))

[1 2 3 4]
[5 6 7 8]
<class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [5]:
np3 = np.arange(9,31,2)
print(np3)

[ 9 11 13 15 17 19 21 23 25 27 29]


In [6]:
np4 = np.linspace(1,15,3)
print(np4)

[ 1.  8. 15.]


In [7]:
np5 = np.zeros((5,))
print(np5)

[0. 0. 0. 0. 0.]


In [9]:
np6 = np.ones((5,))
print(np6)

[1. 1. 1. 1. 1.]


In [10]:
np7 = np.ones((5,2))
print(np7)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [11]:
listdata = [[1,2,3,4,5],[6,7,8,9,10]]

np8 = np.array(listdata)
print(np8)
print("dimension", np8.ndim)
print("shape", np8.shape)
print("amount", np8.size)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
dimension 2
shape (2, 5)
amount 10


In [12]:
np9 = np.arange(1,21)
print(np9)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [14]:
np10 = np9.reshape(4,5)
print(np10)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
